# Generated by Django 5.1.4 on 2024-12-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_finalize_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
