# Generated by Django 5.1.4 on 2024-12-25 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_paystack_reference_alter_order_invoice_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="invoice_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paystack_reference",
        ),
    ]
