# Generated by Django 5.1.4 on 2024-12-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_remove_order_invoice_number_remove_order_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
