# Generated by Django 5.1.4 on 2025-01-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("hair_extensions", "Hair Extensions"),
                    ("wigs", "Wigs"),
                    ("hair_care_products", "Hair Care Products"),
                    ("styling_tools", "Styling Tools"),
                ],
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
