# Generated by Django 5.1.4 on 2025-01-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_category_name_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("hair_care_products", "Hair Care Products"),
                    ("hair_extensions", "Hair Extensions"),
                    ("styling_tools", "Styling Tools"),
                    ("wigs", "Wigs"),
                ],
                max_length=200,
                unique=True,
            ),
        ),
    ]
