# Generated by Django 5.1.4 on 2025-01-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Check to display this product on the homepage"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Meta description for SEO (max 160 characters)",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_keywords",
            field=models.CharField(
                blank=True, help_text="Comma-separated keywords for SEO", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["featured"], name="products_pr_feature_55f52f_idx"
            ),
        ),
    ]
